#ifndef RISCBENCH_RUN_CONFIG_H
#define RISCBENCH_RUN_CONFIG_H

#define RISCBENCH_AUTORUN 1
#define RISCBENCH_MODE 0
#define RISCBENCH_SIZE 1024
#define RISCBENCH_PRECISION 4
#define RISCBENCH_TRACE 0
#define RISCBENCH_ALPHA_BITS 0x00000002u
#define RISCBENCH_MATMUL_PATTERN 0
#define RISCBENCH_AUTORUN_DELAY_US 0u

#endif
